// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNpcgKdXiUz9vK99Uh42Da6_TNeagRiA',
    appId: '1:908874828956:web:fa14362c243340a4083159',
    messagingSenderId: '908874828956',
    projectId: 'trackmoney-af0db',
    authDomain: 'trackmoney-af0db.firebaseapp.com',
    storageBucket: 'trackmoney-af0db.appspot.com',
    measurementId: 'G-ED51Q20JF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa7_65ACPCvtrGHWMh2Hiexuoalbk4Fc',
    appId: '1:908874828956:android:05004579ec07c3b1083159',
    messagingSenderId: '908874828956',
    projectId: 'trackmoney-af0db',
    storageBucket: 'trackmoney-af0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NA3BMSks0UdXuWPyixxU9unE_XMUpuI',
    appId: '1:908874828956:ios:4683c116a411643d083159',
    messagingSenderId: '908874828956',
    projectId: 'trackmoney-af0db',
    storageBucket: 'trackmoney-af0db.appspot.com',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NA3BMSks0UdXuWPyixxU9unE_XMUpuI',
    appId: '1:908874828956:ios:4683c116a411643d083159',
    messagingSenderId: '908874828956',
    projectId: 'trackmoney-af0db',
    storageBucket: 'trackmoney-af0db.appspot.com',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNpcgKdXiUz9vK99Uh42Da6_TNeagRiA',
    appId: '1:908874828956:web:30c2ffc8ba2b04f2083159',
    messagingSenderId: '908874828956',
    projectId: 'trackmoney-af0db',
    authDomain: 'trackmoney-af0db.firebaseapp.com',
    storageBucket: 'trackmoney-af0db.appspot.com',
    measurementId: 'G-Z3719SDD2N',
  );
}
